baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Franco Corona
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Curriculum Vitae
          url: cv.pdf
          weight: 1 
        - name: Photography
          url: photo/
          weight: 2
        - name: Training
          url: training/
          weight: 3
        - name: Cooking
          url: cooking/
          weight: 4 
        - name: Tennis
          url: https://en.wikipedia.org/wiki/Tennis
          weight: 5
        - name: Swimming
          url: https://en.wikipedia.org/wiki/Swimming
          weight: 6
        - name: Japanese
          url: nihongo/
          weight: 7
        - name: English
          url: english/
          weight: 8

params:
    description: "Data Lead | BI & Data Engineering | Data Strategy | Cloud Data Architecture | AWS | GCP"
    author: Franco Corona
    googleAnalyticsID: "G-27CR8RGKW7"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["cv","photo","cooking","blog"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Franco Corona
          subtitle: "Data Lead with 8+ years of experience in data architecture, business intelligence, and cloud platforms (GCP, AWS). I design and optimize scalable data solutions, migrating OnPrem systems to the cloud and reducing processing times from days to hours with cost savings of up to 4X. Specialist in data governance, KPI standardization, and data quality for strategic decision-making. I have led teams in companies such as Linio and Falabella, collaborating with cross-functional areas in e-commerce and retail. I combine leadership with hands-on execution in SQL, Python, Airflow, and BigQuery, promoting collaboration between technical and business teams. My goal is to build data-driven environments where strategy and technical excellence generate measurable impact on eﬃciency, visibility, and growth."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Franco Corona
          buttons:
            #- name: Papers
            #  url: papers/
            #- name: Courses
            #  url: courses/
            - name: Data
              url: data/
            - name: Photography
              url: photo/
            - name: Resume
              url: cv.pdf
            #- name: Archive
            #  url: archive/
            - name: English
              url: english/
            - name: 日本語
              url: nihongo/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:fcorona@outlook.com
        #- name: Zoom
        #  url: https://www.zoom.us
        #- name: Location
        #  url: location/
        #- name: Office Hours
        #  url: officehours/
        #- name: Google Scholar
        #  url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/exibios
        #- name: Substack
        #  url: https://pmichaillat.substack.com
        #- name: YouTube
        #  url: https://www.youtube.com/@alexandermccallsmithoffici9000
        - name: Twitter
          url: https://twitter.com/ocxs
        - name: LinkedIn
          url: https://www.linkedin.com/in/fcoronah/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Franco Corona"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
